version: '3'
services:
  go:
    container_name: go_app
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run cmd/server/main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - "db"
    networks:
      - mynet

  db:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - mynet

volumes:
  db-data:
    driver: local

networks:
    mynet:
      driver: "bridge"