name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SetUp Docker Compose
        run: |
          sudo apt-get install -y docker-compose
          sudo service docker start

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build

